name: my-gitlab

services:
  gitlab:
    container_name: gitlab
    image: gitlab/gitlab-ce:latest
    restart: unless-stopped
    hostname: 'gitlab'
    ports:
      - '80:80'
      - '443:443'
      - '2222:22'
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
    networks:
      - gitlab-network
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab'
        nginx['listen_address'] = '0.0.0.0'
        gitlab_rails['time_zone'] = 'UTC'
        gitlab_rails['gitlab_default_can_create_group'] = true
        gitlab_rails['gitlab_signup_enabled'] = true
        gitlab_rails['gitlab_sign_in_enabled'] = true
        gitlab_rails['ssh_port'] = 2222
        gitlab_kas['enable'] = false
        letsencrypt['enable'] = false

  gitlab-runner:
    container_name: gitlab-runner
    image: gitlab/gitlab-runner:latest
    restart: unless-stopped
    depends_on:
      - gitlab
    networks:
      - gitlab-network
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '$GITLAB_HOME/gitlab-runner/config:/etc/gitlab-runner'
      - '$GITLAB_HOME/gitlab-runner/logs:/var/log/gitlab-runner'

networks:
  gitlab-network:
    driver: bridge
